language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm test
  - npm run build
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sakuru_git_token
  local_dir: build
  on:
    branch: master
