language: node_js
node_js:
  - 'stable'

script:
  - npm run install:peers
  - npm run lint
  - npm run test:ci
  - npm run build

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sakuru_git_token
  local_dir: build
  on:
    branch: master
